# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- azure-pipelines-poc

strategy:
  matrix:
    windows-stable:
      imageName: 'vs2017-win2016'
      rustup_toolchain: stable
    mac-stable:
      imageName: 'macos-10.13'
      rustup_toolchain: stable
    linux-stable:
      imageName: 'ubuntu-16.04'
      rustup_toolchain: stable 

pool:
    vmImage: $(imageName)

steps:
- script: |
    echo $IMAGENAME $RUSTUP_TOOLCHAIN
    condition: ne( variables['Agent.OS'], 'Windows_NT' )
    displayName: 'Non-Windows script'

- script: |
    echo $IMAGENAME $RUSTUP_TOOLCHAIN
    condition: eq( variables['Agent.OS'], 'Windows_NT' )
  displayName: 'Windows script'
